### ISSUE TITLE
Full dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/CrySense#1]
Write a jupyter(.ipynb) file with code to merge all the different voices in different folders into one place(either a folder or dataframe or csv file). All approaches are welcome!!

**Comment by smty2018** [comment]
@SrijanShovit can you please assign this to me

**Comment by Melange-Lf** [comment]
I can contribute here. Just to clarify, a dataset where the individual elements refer(access info) to the individual files in some way, right?

**Comment by SrijanShovit** [comment]
@smty2018 Assigned to you on a FCFS basis. Kindly proceed and keep me updated

**Comment by SrijanShovit** [comment]
> I can contribute here. Just to clarify, a dataset where the individual elements refer(access info) to the individual files in some way, right?

Yes @Melange-Lf !! Please wait as if @smty2018 doesn't progress in 2-3 days, I will assign it to you.

**Comment by Melange-Lf** [comment]
is this still available?

**Comment by SrijanShovit** [comment]
@smty2018 What's the status?

**Comment by smty2018** [comment]
> @smty2018 What's the status?

i have exams going on..,you can assign it to the other person..would love to work on  other issues after  sems

**Comment by SrijanShovit** [comment]
ok assigned to @Melange-Lf

**Comment by Melange-Lf** [comment]
@SrijanShovit i need you to review the pull request for this issue
