### ISSUE TITLE
Dataset hunting

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/CrySense#2]
After exploration of the default dataset, you can consider finding other better datasets for this purpose and suggest with proper reason

**Comment by Melange-Lf** [comment]
hey, I think I have found some(2 at the time of writing this) datasets which might be helpful here

**Comment by SrijanShovit** [comment]
assigned to @Melange-Lf 
Please share the datasets that might be helpful

**Comment by Melange-Lf** [comment]
one:
https://data.mendeley.com/datasets/hbppd883sd/1
two:
https://m.datatang.ai/dataset/998

--------------------------------------------------
"potentially" helpful links
three:
https://paperswithcode.com/dataset/dcase-2017 (has cries of sounds mixed with glass breaking and gunshots)
four:
https://zenodo.org/records/401395 (similar to 'three' but (prolly) a different dataset)
five:
https://zenodo.org/records/5003214 (its a study which used sounds of baby cries, but I couldn't see where their original dataset was)
six:
https://appen.co.jp/off-the-shelf-datasets/ (paid)

-------------------------------------
searching website (i haven't thought of/tried all keywords which could be useful, so you can probably search more datasets)
https://zenodo.org/
https://datasetsearch.research.google.com/

Also I'm a participant in CodePeak, my username here is different so i'll just drop an @ in the codepeak discord's CrySense channel.

**Comment by SrijanShovit** [comment]
Looks good @Melange-Lf

**Comment by SrijanShovit** [comment]
You can create a readme and a pull request for that. I will merge it.
