### ISSUE TITLE
Feature enhancement

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/CrySense#7]
Add new features such as spectral contrast, chroma features, or mel-frequency cepstral coefficients (MFCCs)

**Comment by onkar-1432** [comment]
@SrijanShovit can I work on these issue. I have previous experience with this.

**Comment by SrijanShovit** [comment]
Ok @onkar-1432 Do check the dataset and explore the features that you can extract. Good luck!!
Any help needed, ping me here!!

**Comment by onkar-1432** [comment]
@SrijanShovit i have created PR.please check and suggest me changes. Thanks.
